# Определяет формат запроса (кто, что, какое действие) 
[request_definition]
r = sub, obj, act


# Определяет формат политики
[policy_definition] 
p = sub, obj, act


# Определяет формат ролей и группировок (группа g)
[role_definition] 
g = _, _


# Определяет эффект политики (разрешить или запретить)
[policy_effect] 
e = some(where (p.eft == allow))


# Определяет логику сопоставления запроса с политиками, включая дополнительные группировки
[matchers]
m = g(r.sub, p.sub) &&
  r.obj == p.obj &&
  r.act == p.act