"""add_casbin_rule_table

Revision ID: 5593fa91ccb1
Revises: 6a3fddcd6998
Create Date: 2026-05-15 21:48:36.339756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5593fa91ccb1'
down_revision: Union[str, Sequence[str], None] = '6a3fddcd6998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('casbin_rule', 'ptype',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v0',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v1',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v2',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v3',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v4',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v5',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.drop_index(op.f('ix_casbin_rule_ptype'), table_name='casbin_rule')
  op.alter_column('documents', 'converted_to_pdf',
              existing_type=sa.BOOLEAN(),
              server_default=None,
              existing_nullable=True)
  op.alter_column('history_downloads', 'is_success',
              existing_type=sa.BOOLEAN(),
              server_default=None,
              existing_nullable=False)
  op.alter_column('notifications', 'is_read',
              existing_type=sa.BOOLEAN(),
              server_default=None,
              existing_nullable=False)
  op.alter_column('registry_devices', 'is_active',
              existing_type=sa.BOOLEAN(),
              server_default=None,
              existing_nullable=False)
  op.alter_column('users', 'mfa_enabled',
              existing_type=sa.BOOLEAN(),
              server_default=None,
              existing_nullable=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('users', 'mfa_enabled',
              existing_type=sa.BOOLEAN(),
              server_default=sa.text('false'),
              existing_nullable=False)
  op.alter_column('registry_devices', 'is_active',
              existing_type=sa.BOOLEAN(),
              server_default=sa.text('true'),
              existing_nullable=False)
  op.alter_column('notifications', 'is_read',
              existing_type=sa.BOOLEAN(),
              server_default=sa.text('false'),
              existing_nullable=False)
  op.alter_column('history_downloads', 'is_success',
              existing_type=sa.BOOLEAN(),
              server_default=sa.text('false'),
              existing_nullable=False)
  op.alter_column('documents', 'converted_to_pdf',
              existing_type=sa.BOOLEAN(),
              server_default=sa.text('false'),
              existing_nullable=True)
  op.create_index(op.f('ix_casbin_rule_ptype'), 'casbin_rule', ['ptype'], unique=False)
  op.alter_column('casbin_rule', 'v5',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v4',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v3',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v2',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v1',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v0',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'ptype',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  # ### end Alembic commands ###
