"""initial

Revision ID: 811c3e623d7d
Revises: 
Create Date: 2026-05-12 18:22:58.239080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '811c3e623d7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('permissions',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('permission_name', sa.String(length=100), nullable=False),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
  sa.UniqueConstraint('permission_name', name=op.f('uq_permissions_permission_name'))
  )
  op.create_table('roles',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('role_name', sa.String(length=30), nullable=False),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
  sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
  )
  op.create_table('search_tags',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('tag_name', sa.String(length=50), nullable=False),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_search_tags'))
  )
  op.create_index(op.f('ix_search_tags_tag_name'), 'search_tags', ['tag_name'], unique=True)
  op.create_table('roles_permissions',
  sa.Column('role_id', sa.Integer(), nullable=False),
  sa.Column('permission_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_roles_permissions_permission_id_permissions'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_roles_permissions_role_id_roles'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_roles_permissions'))
  )
  op.create_table('users',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('username', sa.String(length=50), nullable=False),
  sa.Column('email', sa.String(length=255), nullable=False),
  sa.Column('password_hash', sa.String(length=255), nullable=False),
  sa.Column('mfa_secret', sa.String(length=255), nullable=True),
  sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()),
  sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
  sa.Column('upload_quota_used', sa.Integer(), nullable=False),
  sa.Column('verification_status', sa.Enum('UNVERIFIED', 'EMAIL_VERIFIED', 'PHONE_VERIFIED', name='verification_enum'), nullable=False),
  sa.Column('account_status', sa.Enum('ACTIVE', 'BLOCKED', 'PENDING_REVIEW', name='account_enum'), nullable=False),
  sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
  sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('role_id', sa.Integer(), nullable=True),
  sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_users_ck_users_failed_login_attempts_positive')),
  sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='SET NULL'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
  sa.UniqueConstraint('email', name=op.f('uq_users_email')),
  sa.UniqueConstraint('username', name=op.f('uq_users_username'))
  )
  op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
  op.create_table('audit_logs',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=True),
  sa.Column('action', sa.String(length=50), nullable=False),
  sa.Column('target_uuid', postgresql.UUID(), nullable=False),
  sa.Column('target_type', sa.Enum('DOCUMENT', 'USER', 'GROUP', 'REPORT', name='audit_enum'), nullable=False),
  sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
  sa.Column('ip_address', postgresql.INET(), nullable=True),
  sa.Column('success', sa.Boolean(), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
  )
  op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
  op.create_table('documents',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('title', sa.String(length=255), nullable=False),
  sa.Column('description', sa.Text(), nullable=True),
  sa.Column('publish_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('uploader_id', sa.Integer(), nullable=False),
  sa.Column('moderator_id', sa.Integer(), nullable=True),
  sa.Column('minio_bucket', sa.String(length=100), nullable=False),
  sa.Column('minio_object_path', sa.String(length=500), nullable=False),
  sa.Column('file_original_name', sa.String(length=255), nullable=True),
  sa.Column('file_mime', sa.String(length=100), nullable=False),
  sa.Column('file_size', sa.BigInteger(), nullable=False),
  sa.Column('file_hash', sa.String(length=64), nullable=False),
  sa.Column('format', sa.String(length=20), nullable=False),
  sa.Column('converted_to_pdf', sa.Boolean(), nullable=True, server_default=sa.false()),
  sa.Column('visibility_status', sa.Enum('PUBLISHED', 'UNLISTED', 'ARCHIVED', name='visibility_enum'), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_documents_moderator_id_users'), ondelete='SET NULL'),
  sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_documents_uploader_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
  )
  op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=True)
  op.create_index(op.f('ix_documents_moderator_id'), 'documents', ['moderator_id'], unique=False)
  op.create_index(op.f('ix_documents_title'), 'documents', ['title'], unique=False)
  op.create_index(op.f('ix_documents_uploader_id'), 'documents', ['uploader_id'], unique=False)
  op.create_table('favorite_folders',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('folder_name', sa.String(length=100), nullable=False),
  sa.Column('description', sa.String(length=500), nullable=True),
  sa.Column('parent_folder_id', sa.Integer(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['parent_folder_id'], ['favorite_folders.id'], name=op.f('fk_favorite_folders_parent_folder_id_favorite_folders'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_folders_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_folders')),
  sa.UniqueConstraint('user_id', 'parent_folder_id', 'folder_name', name='uq_favorite_folder_per_parent')
  )
  op.create_index(op.f('ix_favorite_folders_parent_folder_id'), 'favorite_folders', ['parent_folder_id'], unique=False)
  op.create_index(op.f('ix_favorite_folders_user_id'), 'favorite_folders', ['user_id'], unique=False)
  op.create_table('groups',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('group_name', sa.String(length=100), nullable=False),
  sa.Column('creator_id', sa.Integer(), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_groups_creator_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
  sa.UniqueConstraint('group_name', name=op.f('uq_groups_group_name'))
  )
  op.create_index(op.f('ix_groups_creator_id'), 'groups', ['creator_id'], unique=False)
  op.create_table('notifications',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('source_type', sa.String(length=50), nullable=False),
  sa.Column('source_id', sa.Integer(), nullable=False),
  sa.Column('event_type', sa.String(length=50), nullable=False),
  sa.Column('title', sa.String(length=255), nullable=False),
  sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
  sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', name='notification_channel_enum'), nullable=False),
  sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.false()),
  sa.Column('read_at', sa.DateTime(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('expires_at', sa.DateTime(), nullable=False),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
  )
  op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
  op.create_table('offline_folders',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('folder_name', sa.String(length=100), nullable=False),
  sa.Column('description', sa.String(length=500), nullable=True),
  sa.Column('parent_folder_id', sa.Integer(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['parent_folder_id'], ['offline_folders.id'], name=op.f('fk_offline_folders_parent_folder_id_offline_folders'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_offline_folders_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_folders')),
  sa.UniqueConstraint('user_id', 'parent_folder_id', 'folder_name', name='uq_offline_folder_per_parent')
  )
  op.create_index(op.f('ix_offline_folders_parent_folder_id'), 'offline_folders', ['parent_folder_id'], unique=False)
  op.create_index(op.f('ix_offline_folders_user_id'), 'offline_folders', ['user_id'], unique=False)
  op.create_table('registry_devices',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('device_uuid', postgresql.UUID(), nullable=False),
  sa.Column('device_name', sa.String(length=100), nullable=False),
  sa.Column('platform', sa.String(length=20), nullable=False),
  sa.Column('app_version', sa.String(length=20), nullable=False),
  sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
  sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_registry_devices_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_registry_devices')),
  sa.UniqueConstraint('device_uuid', name=op.f('uq_registry_devices_device_uuid'))
  )
  op.create_index(op.f('ix_registry_devices_user_id'), 'registry_devices', ['user_id'], unique=False)
  op.create_table('reports',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('reporter_id', sa.Integer(), nullable=False),
  sa.Column('target_type', sa.Enum('DOCUMENT', 'USER', 'GROUP', name='report_target_enum'), nullable=False),
  sa.Column('target_id', sa.Integer(), nullable=False),
  sa.Column('reason_category', sa.Enum('COPYRIGHT', 'INAPPROPRIATE', 'VIRUS', 'OTHER', name='report_category_enum'), nullable=False),
  sa.Column('description', sa.Text(), nullable=True),
  sa.Column('report_status', sa.Enum('PENDING', 'IN_REVIEW', 'RESOLVED', 'REJECTED', name='report_enum'), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('resolved_at', sa.DateTime(), nullable=True),
  sa.Column('resolved_by', sa.Integer(), nullable=True),
  sa.Column('resolution_note', sa.Text(), nullable=True),
  sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_reports_resolved_by_users'), ondelete='SET NULL'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
  )
  op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
  op.create_index(op.f('ix_reports_resolved_by'), 'reports', ['resolved_by'], unique=False)
  op.create_table('upload_requests',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('title', sa.String(length=255), nullable=False),
  sa.Column('description', sa.Text(), nullable=True),
  sa.Column('uploader_id', sa.Integer(), nullable=False),
  sa.Column('moderator_id', sa.Integer(), nullable=True),
  sa.Column('temporary_minio_path', sa.String(length=500), nullable=False),
  sa.Column('file_original_name', sa.String(length=255), nullable=True),
  sa.Column('file_mime', sa.String(length=100), nullable=False),
  sa.Column('file_size', sa.BigInteger(), nullable=False),
  sa.Column('file_hash', sa.String(length=64), nullable=False),
  sa.Column('workflow_status', sa.Enum('UPLOADED', 'PROCESSING', 'PENDING_REVIEW', 'ACCEPTED', 'REJECTED', name='workflow_enum'), nullable=False),
  sa.Column('rejection_reason', sa.Text(), nullable=True),
  sa.Column('processing_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_upload_requests_moderator_id_users'), ondelete='SET NULL'),
  sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_upload_requests_uploader_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_upload_requests'))
  )
  op.create_index(op.f('ix_upload_requests_file_hash'), 'upload_requests', ['file_hash'], unique=True)
  op.create_index(op.f('ix_upload_requests_moderator_id'), 'upload_requests', ['moderator_id'], unique=False)
  op.create_index(op.f('ix_upload_requests_uploader_id'), 'upload_requests', ['uploader_id'], unique=False)
  op.create_table('conversion_jobs',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('source_entity_id', sa.Integer(), nullable=True),
  sa.Column('document_id', sa.Integer(), nullable=True),
  sa.Column('conversion_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'RETRYING', name='conversion_enum'), nullable=False),
  sa.Column('original_format', sa.String(length=20), nullable=False),
  sa.Column('target_format', sa.String(length=20), nullable=False),
  sa.Column('retry_count', sa.Integer(), nullable=False),
  sa.Column('error_log', sa.Text(), nullable=True),
  sa.Column('output_minio_path', sa.String(length=500), nullable=True),
  sa.Column('started_at', sa.DateTime(), nullable=True),
  sa.Column('completed_at', sa.DateTime(), nullable=True),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_conversion_jobs_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['source_entity_id'], ['upload_requests.id'], name=op.f('fk_conversion_jobs_source_entity_id_upload_requests'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_conversion_jobs'))
  )
  op.create_index(op.f('ix_conversion_jobs_document_id'), 'conversion_jobs', ['document_id'], unique=False)
  op.create_index(op.f('ix_conversion_jobs_source_entity_id'), 'conversion_jobs', ['source_entity_id'], unique=False)
  op.create_table('documents_search_tags',
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.Column('tag_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_documents_search_tags_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['tag_id'], ['search_tags.id'], name=op.f('fk_documents_search_tags_tag_id_search_tags'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('document_id', 'tag_id', name=op.f('pk_documents_search_tags'))
  )
  op.create_table('favorite_items',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.Column('folder_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_favorite_items_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['folder_id'], ['favorite_folders.id'], name=op.f('fk_favorite_items_folder_id_favorite_folders'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_favorite_items'))
  )
  op.create_index(op.f('ix_favorite_items_document_id'), 'favorite_items', ['document_id'], unique=False)
  op.create_index(op.f('ix_favorite_items_folder_id'), 'favorite_items', ['folder_id'], unique=False)
  op.create_table('group_invitations',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('group_id', sa.Integer(), nullable=False),
  sa.Column('invited_email', sa.String(length=255), nullable=False),
  sa.Column('token', sa.String(length=64), nullable=False),
  sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('invitation_status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitation_enum'), nullable=False),
  sa.Column('created_by', sa.Integer(), nullable=True),
  sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_group_invitations_created_by_users'), ondelete='SET NULL'),
  sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_invitations_group_id_groups'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_group_invitations')),
  sa.UniqueConstraint('token', name=op.f('uq_group_invitations_token'))
  )
  op.create_index(op.f('ix_group_invitations_created_by'), 'group_invitations', ['created_by'], unique=False)
  op.create_index(op.f('ix_group_invitations_group_id'), 'group_invitations', ['group_id'], unique=False)
  op.create_table('group_materials',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('group_id', sa.Integer(), nullable=False),
  sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('sender_id', sa.Integer(), nullable=True),
  sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_materials_group_id_groups'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_group_materials_sender_id_users'), ondelete='SET NULL'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_group_materials'))
  )
  op.create_index(op.f('ix_group_materials_group_id'), 'group_materials', ['group_id'], unique=False)
  op.create_index(op.f('ix_group_materials_sender_id'), 'group_materials', ['sender_id'], unique=False)
  op.create_table('groups_users',
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('group_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_users_group_id_groups'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_users_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_groups_users'))
  )
  op.create_table('history_downloads',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=True),
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('ip_address', postgresql.INET(), nullable=True),
  sa.Column('user_agent', sa.Text(), nullable=True),
  sa.Column('download_type', sa.Enum('PREVIEW', 'FULL', 'EXPORT', name='download_enum'), nullable=False),
  sa.Column('is_success', sa.Boolean(), nullable=False, server_default=sa.false()),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_history_downloads_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_history_downloads_user_id_users'), ondelete='SET NULL'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_history_downloads'))
  )
  op.create_index(op.f('ix_history_downloads_document_id'), 'history_downloads', ['document_id'], unique=False)
  op.create_index(op.f('ix_history_downloads_downloaded_at'), 'history_downloads', ['downloaded_at'], unique=False)
  op.create_index(op.f('ix_history_downloads_user_id'), 'history_downloads', ['user_id'], unique=False)
  op.create_table('history_versions',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.Column('version_number', sa.Integer(), nullable=False),
  sa.Column('minio_path', sa.String(length=500), nullable=False),
  sa.Column('minio_bucket', sa.String(length=100), nullable=False),
  sa.Column('file_hash', sa.String(length=64), nullable=False),
  sa.Column('file_size', sa.BigInteger(), nullable=False),
  sa.Column('file_format', sa.String(length=20), nullable=False),
  sa.Column('uploaded_by', sa.Integer(), nullable=True),
  sa.Column('change_notes', sa.Text(), nullable=True),
  sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_history_versions_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_history_versions_uploaded_by_users'), ondelete='SET NULL'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_history_versions')),
  sa.UniqueConstraint('document_id', 'version_number', name='uq_document_id_and_version_number'),
  sa.UniqueConstraint('file_hash', name=op.f('uq_history_versions_file_hash'))
  )
  op.create_index(op.f('ix_history_versions_document_id'), 'history_versions', ['document_id'], unique=False)
  op.create_index(op.f('ix_history_versions_uploaded_by'), 'history_versions', ['uploaded_by'], unique=False)
  op.create_index(op.f('ix_history_versions_version_number'), 'history_versions', ['version_number'], unique=False)
  op.create_table('history_views',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_history_views_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_history_views_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_history_views'))
  )
  op.create_index(op.f('ix_history_views_document_id'), 'history_views', ['document_id'], unique=False)
  op.create_index(op.f('ix_history_views_user_id'), 'history_views', ['user_id'], unique=False)
  op.create_table('moderation_assignments',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('upload_requests_id', sa.Integer(), nullable=False),
  sa.Column('moderator_id', sa.Integer(), nullable=True),
  sa.Column('deadline', sa.DateTime(), nullable=False),
  sa.Column('priority_score', sa.Integer(), nullable=False),
  sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
  sa.Column('completed_at', sa.DateTime(), nullable=True),
  sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('fk_moderation_assignments_moderator_id_users'), ondelete='SET NULL'),
  sa.ForeignKeyConstraint(['upload_requests_id'], ['upload_requests.id'], name=op.f('fk_moderation_assignments_upload_requests_id_upload_requests'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_moderation_assignments'))
  )
  op.create_index(op.f('ix_moderation_assignments_moderator_id'), 'moderation_assignments', ['moderator_id'], unique=False)
  op.create_index(op.f('ix_moderation_assignments_upload_requests_id'), 'moderation_assignments', ['upload_requests_id'], unique=False)
  op.create_table('offline_items',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.Column('folder_id', sa.Integer(), nullable=False),
  sa.Column('local_file_hash_checksum', sa.String(length=64), nullable=False),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_offline_items_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['folder_id'], ['offline_folders.id'], name=op.f('fk_offline_items_folder_id_offline_folders'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_offline_items'))
  )
  op.create_index(op.f('ix_offline_items_document_id'), 'offline_items', ['document_id'], unique=False)
  op.create_index(op.f('ix_offline_items_folder_id'), 'offline_items', ['folder_id'], unique=False)
  op.create_table('sync_states',
  sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
  sa.Column('user_id', sa.Integer(), nullable=False),
  sa.Column('device_id', sa.Integer(), nullable=False),
  sa.Column('entity_type', sa.String(length=20), nullable=False),
  sa.Column('entity_id', postgresql.UUID(), nullable=False),
  sa.Column('local_checksum', sa.String(length=64), nullable=False),
  sa.Column('server_checksum', sa.String(length=64), nullable=False),
  sa.Column('last_sync_at', sa.DateTime(), nullable=False),
  sa.Column('network_status', sa.Enum('SYNCED', 'PENDING', 'CONFLICT', 'DELETED_LOCALLY', name='network_enum'), nullable=False),
  sa.Column('conflict_resolution', sa.Enum('SERVER_WINS', 'CLIENT_WINS', 'MERGE', name='conflict_resolution_enum'), nullable=False),
  sa.ForeignKeyConstraint(['device_id'], ['registry_devices.id'], name=op.f('fk_sync_states_device_id_registry_devices'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_states_user_id_users'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_states'))
  )
  op.create_index(op.f('ix_sync_states_device_id'), 'sync_states', ['device_id'], unique=False)
  op.create_index(op.f('ix_sync_states_user_id'), 'sync_states', ['user_id'], unique=False)
  op.create_table('group_material_documents',
  sa.Column('material_id', sa.Integer(), nullable=False),
  sa.Column('document_id', sa.Integer(), nullable=False),
  sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_group_material_documents_document_id_documents'), ondelete='CASCADE'),
  sa.ForeignKeyConstraint(['material_id'], ['group_materials.id'], name=op.f('fk_group_material_documents_material_id_group_materials'), ondelete='CASCADE'),
  sa.PrimaryKeyConstraint('material_id', 'document_id', name=op.f('pk_group_material_documents'))
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('group_material_documents')
  op.drop_index(op.f('ix_sync_states_user_id'), table_name='sync_states')
  op.drop_index(op.f('ix_sync_states_device_id'), table_name='sync_states')
  op.drop_table('sync_states')
  op.drop_index(op.f('ix_offline_items_folder_id'), table_name='offline_items')
  op.drop_index(op.f('ix_offline_items_document_id'), table_name='offline_items')
  op.drop_table('offline_items')
  op.drop_index(op.f('ix_moderation_assignments_upload_requests_id'), table_name='moderation_assignments')
  op.drop_index(op.f('ix_moderation_assignments_moderator_id'), table_name='moderation_assignments')
  op.drop_table('moderation_assignments')
  op.drop_index(op.f('ix_history_views_user_id'), table_name='history_views')
  op.drop_index(op.f('ix_history_views_document_id'), table_name='history_views')
  op.drop_table('history_views')
  op.drop_index(op.f('ix_history_versions_version_number'), table_name='history_versions')
  op.drop_index(op.f('ix_history_versions_uploaded_by'), table_name='history_versions')
  op.drop_index(op.f('ix_history_versions_document_id'), table_name='history_versions')
  op.drop_table('history_versions')
  op.drop_index(op.f('ix_history_downloads_user_id'), table_name='history_downloads')
  op.drop_index(op.f('ix_history_downloads_downloaded_at'), table_name='history_downloads')
  op.drop_index(op.f('ix_history_downloads_document_id'), table_name='history_downloads')
  op.drop_table('history_downloads')
  op.drop_table('groups_users')
  op.drop_index(op.f('ix_group_materials_sender_id'), table_name='group_materials')
  op.drop_index(op.f('ix_group_materials_group_id'), table_name='group_materials')
  op.drop_table('group_materials')
  op.drop_index(op.f('ix_group_invitations_group_id'), table_name='group_invitations')
  op.drop_index(op.f('ix_group_invitations_created_by'), table_name='group_invitations')
  op.drop_table('group_invitations')
  op.drop_index(op.f('ix_favorite_items_folder_id'), table_name='favorite_items')
  op.drop_index(op.f('ix_favorite_items_document_id'), table_name='favorite_items')
  op.drop_table('favorite_items')
  op.drop_table('documents_search_tags')
  op.drop_index(op.f('ix_conversion_jobs_source_entity_id'), table_name='conversion_jobs')
  op.drop_index(op.f('ix_conversion_jobs_document_id'), table_name='conversion_jobs')
  op.drop_table('conversion_jobs')
  op.drop_index(op.f('ix_upload_requests_uploader_id'), table_name='upload_requests')
  op.drop_index(op.f('ix_upload_requests_moderator_id'), table_name='upload_requests')
  op.drop_index(op.f('ix_upload_requests_file_hash'), table_name='upload_requests')
  op.drop_table('upload_requests')
  op.drop_index(op.f('ix_reports_resolved_by'), table_name='reports')
  op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
  op.drop_table('reports')
  op.drop_index(op.f('ix_registry_devices_user_id'), table_name='registry_devices')
  op.drop_table('registry_devices')
  op.drop_index(op.f('ix_offline_folders_user_id'), table_name='offline_folders')
  op.drop_index(op.f('ix_offline_folders_parent_folder_id'), table_name='offline_folders')
  op.drop_table('offline_folders')
  op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
  op.drop_table('notifications')
  op.drop_index(op.f('ix_groups_creator_id'), table_name='groups')
  op.drop_table('groups')
  op.drop_index(op.f('ix_favorite_folders_user_id'), table_name='favorite_folders')
  op.drop_index(op.f('ix_favorite_folders_parent_folder_id'), table_name='favorite_folders')
  op.drop_table('favorite_folders')
  op.drop_index(op.f('ix_documents_uploader_id'), table_name='documents')
  op.drop_index(op.f('ix_documents_title'), table_name='documents')
  op.drop_index(op.f('ix_documents_moderator_id'), table_name='documents')
  op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
  op.drop_table('documents')
  op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
  op.drop_table('audit_logs')
  op.drop_index(op.f('ix_users_role_id'), table_name='users')
  op.drop_table('users')
  op.drop_table('roles_permissions')
  op.drop_index(op.f('ix_search_tags_tag_name'), table_name='search_tags')
  op.drop_table('search_tags')
  op.drop_table('roles')
  op.drop_table('permissions')
  
  op.execute("DROP TYPE IF EXISTS verification_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS account_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS visibility_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS workflow_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS invitation_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS report_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS report_category_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS report_target_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS conversion_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS download_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS audit_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS notification_channel_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS network_enum CASCADE")
  op.execute("DROP TYPE IF EXISTS conflict_resolution_enum CASCADE")
  # ### end Alembic commands ###
