"""correction models

Revision ID: c832d60122ed
Revises: 5593fa91ccb1
Create Date: 2026-05-15 22:18:12.542464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c832d60122ed'
down_revision: Union[str, Sequence[str], None] = '5593fa91ccb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_history_versions_document_id'), table_name='history_versions')
  op.drop_index(op.f('ix_history_versions_version_number'), table_name='history_versions')
  op.create_index(
    'ix_moderation_assignments_deadline_priority',
    'moderation_assignments',
    ['deadline', 'priority_score']
  )
  op.create_index(op.f('ix_reports_report_status'), 'reports', ['report_status'], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f('ix_moderation_assignments_deadline_priority'), table_name='moderation_assignments')
  op.drop_index(op.f('ix_reports_report_status'), table_name='reports')
  op.create_index(op.f('ix_history_versions_version_number'), 'history_versions', ['version_number'], unique=False)
  op.create_index(op.f('ix_history_versions_document_id'), 'history_versions', ['document_id'], unique=False)
  # ### end Alembic commands ###
