"""correction casbin table

Revision ID: f2df2cce10b0
Revises: c832d60122ed
Create Date: 2026-05-16 10:58:49.268733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2df2cce10b0'
down_revision: Union[str, Sequence[str], None] = 'c832d60122ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('casbin_rule', 'ptype',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v0',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v1',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v2',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v3',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v4',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.alter_column('casbin_rule', 'v5',
              existing_type=sa.VARCHAR(length=255),
              nullable=True)
  op.drop_index(op.f('ix_moderation_assignments_deadline_priority'), table_name='moderation_assignments')
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_index(op.f('ix_moderation_assignments_deadline_priority'), 'moderation_assignments', ['deadline', 'priority_score'], unique=False)
  op.alter_column('casbin_rule', 'v5',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v4',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v3',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v2',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v1',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'v0',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  op.alter_column('casbin_rule', 'ptype',
              existing_type=sa.VARCHAR(length=255),
              nullable=False)
  # ### end Alembic commands ###
